export const SIGN_UP_PENDING = "SIGN_UP_PENDING"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAIL = "SIGN_UP_FAIL"

export const SIGN_IN_PENDING = "SIGN_IN_PENDING"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_FAIL = "SIGN_IN_FAIL"
export const SIGN_OUT = "SIGN_OUT"

export const FORGOT_PASSWORD_PENDING = "FORGOT_PASSWORD_PENDING"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

export const SEARCH_PENDING = "SEARCH_PENDING"
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const SEARCH_FAILURE = "SEARCH_FAILURE"

export const CREATE_ISSUE_PENDING = "CREATE_ISSUE_PENDING"
export const CREATE_ISSUE_SUCCESS = "CREATE_ISSUE_SUCCESS"
export const CREATE_ISSUE_FAILURE = "CREATE_ISSUE_FAILURE"

export const MY_ISSUES_PENDING = "MY_ISSUES_PENDING"
export const MY_ISSUES_SUCCESS = "MY_ISSUES_SUCCESS"
export const MY_ISSUES_FAILURE = "MY_ISSUES_FAILURE"